SSOConfig:
    Default:
        SSORegion: us-east-1
        StartUrl: https://masterpoint.awsapps.com/start
DefaultSSO: Default
SecureStore: json
DefaultRegion: us-east-1
ConsoleDuration: 720
CacheRefresh: 168
AutoConfigCheck: true
UrlAction: print
ConfigProfilesUrlAction: clip
LogLevel: error
HistoryLimit: 10
HistoryMinutes: 1440
AccountPrimaryTag:
    - AccountName
    - AccountAlias
    - Email
PromptColors:
    descriptionbgcolor: Turquoise
    descriptiontextcolor: Black
    inputbgcolor: DefaultColor
    inputtextcolor: DefaultColor
    prefixbackgroundcolor: DefaultColor
    prefixtextcolor: Blue
    previewsuggestionbgcolor: DefaultColor
    previewsuggestiontextcolor: Green
    scrollbarbgcolor: Cyan
    scrollbarthumbcolor: LightGrey
    selecteddescriptionbgcolor: DarkGray
    selecteddescriptiontextcolor: White
    selectedsuggestionbgcolor: DarkGray
    selectedsuggestiontextcolor: White
    suggestionbgcolor: Cyan
    suggestiontextcolor: White
ListFields:
    - AccountIdPad
    - AccountAlias
    - RoleName
    - Profile
    - Expires
