name: Trunk Check

on:
  workflow_call:
    inputs:
      setup-deps:
        description: Setup dependencies for trunk check (npm install, etc. Needed for eslint extensions and similar)
        default: false
        required: false
        type: boolean

permissions:
  actions: read
  checks: write
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: trunk-io/trunk-action@e1234e67a86010d61ddac8d8ebf4b783e2ffd2fa # v2.0.0
        with:
          setup-deps: ${{ inputs.setup-deps }}
