name: Trunk Check

on:
  workflow_call:

permissions:
  actions: read
  checks: write
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: trunk-io/trunk-action@v1
