name: Trunk Check

on:
  workflow_call:
    inputs:
      setup-deps:
        description: Setup dependencies
        default: "false"
        required: false
        type: boolean

permissions:
  actions: read
  checks: write
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: trunk-io/trunk-action@v1
        with:
          setup-deps: ${{ inputs.setup-deps }}
