name: Trunk Check

on:
  workflow_call:
    inputs:
      setup-deps:
        description: Setup dependencies for trunk check (npm install, etc. Needed for eslint extensions and similar)
        default: false
        required: false
        type: boolean

permissions:
  actions: read
  checks: write
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: trunk-io/trunk-action@v1
        with:
          setup-deps: ${{ inputs.setup-deps }}
