name: Trunk Check

on:
  workflow_call:
    inputs:
      setup-deps:
        description: Setup dependencies for trunk check (npm install, etc. Needed for eslint extensions and similar)
        default: false
        required: false
        type: boolean

permissions:
  actions: read
  checks: write
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: trunk-io/trunk-action@4d5ecc89b2691705fd08c747c78652d2fc806a94 # v1.1.19
        with:
          setup-deps: ${{ inputs.setup-deps }}
